/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ConnectionDB;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Admins
 */
public class CTHoaDon extends javax.swing.JFrame {
    
    ConnectionDB c=new ConnectionDB();
    Connection cn=c.getConnectionDB();
    Statement stm=null;
    ResultSet rs=null;
    PreparedStatement ps=null;
    String sql,MaHD;
    DefaultTableModel dtm=new DefaultTableModel();
    public CTHoaDon(String MaHD) {
        initComponents();
        this.MaHD=MaHD;
        this.setLocationRelativeTo(null);
        ShowTB.setModel(dtm);
        dtm.setColumnCount(0);
        dtm.setRowCount(0);
        dtm.addColumn("Mã món");
        dtm.addColumn("Số lượng");
        dtm.addColumn("Mã thịt 1");
        dtm.addColumn("Mã thịt 2");
        dtm.addColumn("Mã thịt 3");
        dtm.addColumn("Mã thịt 4");
        dtm.addColumn("Thành tiền");
        dtm.addColumn("Ghi chú");
        ShowTB.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        ShowTB.getColumnModel().getColumn(0).setPreferredWidth(60);
        ShowTB.getColumnModel().getColumn(1).setPreferredWidth(70);
        ShowTB.getColumnModel().getColumn(2).setPreferredWidth(60);
        ShowTB.getColumnModel().getColumn(3).setPreferredWidth(60);
        ShowTB.getColumnModel().getColumn(4).setPreferredWidth(60);
        ShowTB.getColumnModel().getColumn(5).setPreferredWidth(60);
        ShowTB.getColumnModel().getColumn(6).setPreferredWidth(85);
        ShowTB.getColumnModel().getColumn(7).setPreferredWidth(78);   
        try {
            sql="select * from CT_HOA_DON where MaHD="+MaHD;
            stm=cn.createStatement();
            rs=stm.executeQuery(sql);
            while(rs.next()) {
                dtm.addRow(new Object[] {rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)});
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ShowTB = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        ShowTB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(ShowTB);

        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i,t3,t8;
        String t2,t4,t5,t6,t7;
        try {
            sql="delete from CT_HOA_DON where MaHD="+MaHD;
            ps=cn.prepareStatement(sql);
            ps.executeUpdate();
            for(i=0;i<dtm.getRowCount();i++){
                sql="insert into CT_HOA_DON values (?,?,?,?,?,?,?,?,?)";
                ps=cn.prepareStatement(sql);
                t2=(dtm.getValueAt(i,0)).toString();
                t3=Integer.parseInt((dtm.getValueAt(i,1)).toString());
                t4=(dtm.getValueAt(i,2)).toString();
                t5=(dtm.getValueAt(i,3)).toString();
                t6= (dtm.getValueAt(i,4)).toString();
                t7=(dtm.getValueAt(i,5)).toString();
                t8=Integer.parseInt((dtm.getValueAt(i,6)).toString());
                System.out.println(t8);
                ps.setInt(1,Integer.parseInt(MaHD));
                ps.setString(2,t2);
                ps.setInt(3,t3);
                ps.setString(4,t4);
                ps.setString(5,t5);
                ps.setString(6,t6);
                ps.setString(7,t7);
                ps.setInt(8,t8);
                try {
                    ps.setString(9,(ShowTB.getValueAt(i,7)).toString());
                } catch (Exception e) {
                    ps.setString(9,"<none>");
                    e.printStackTrace();
                }
                ps.executeUpdate();
                
            }
            JOptionPane.showMessageDialog(this, "Đã lưu chỉnh sửa");
            sql="update HOADON set ThanhTien=(select sum(DonGia) from CT_HOA_DON where MaHD="+MaHD+") where MaHD="+MaHD;
            ps=cn.prepareStatement(sql);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CTHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CTHoaDon("1").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ShowTB;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
