/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.*;
import java.io.*; 
import control.ConnectionDB;
import javax.swing.JOptionPane;
/**
 *
 * @author Admins
 */
public class login extends javax.swing.JFrame {
    static String acc,pass;
    public login() {
        initComponents();
        this.setLocationRelativeTo(null);  
        try {
            BufferedReader reader = new BufferedReader(new FileReader("..\\QL_PHO\\test\\RmbAcc.txt"));
            if ((acc=reader.readLine())==null) {
                acc="";
            }
            if ((pass=reader.readLine())==null) {
                pass="";
            }
            PosCB.setSelectedItem(reader.readLine());
            reader.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        AccTF.setText(acc);
        PassTF.setText(pass);
        if (!acc.equals("") && !pass.equals("")) {
            RememberRB.setSelected(true);
        }
    }
    public login(String a,String p) {
        initComponents();
        this.setLocationRelativeTo(null);
        AccTF.setText(a);
        PassTF.setText(p);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AccTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PassTF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        RememberRB = new javax.swing.JRadioButton();
        ForgetBT = new javax.swing.JButton();
        RegisterBT = new javax.swing.JButton();
        LoginBT = new javax.swing.JButton();
        ResetBT = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        PosCB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/unnamed.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 512, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 51)));

        jLabel1.setFont(new java.awt.Font("UVF Reina 12 Pro", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText(" Phở Swing");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        AccTF.setToolTipText("Hãy nhập tên tài khoản của bạn.");

        jLabel2.setFont(new java.awt.Font("UVF Walbaum MT Std Medium", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 51));
        jLabel2.setText("Chào mừng bạn đã trở lạii!");

        jLabel3.setFont(new java.awt.Font("UVF Salome", 0, 14)); // NOI18N
        jLabel3.setText("TÀI KHOẢN");

        jLabel4.setFont(new java.awt.Font("UVF Salome", 0, 14)); // NOI18N
        jLabel4.setText("MẬT KHẨU");

        RememberRB.setText("Lưu mật khẩu?");
        RememberRB.setToolTipText("Lưu mật khẩu cho lần đăng nhập kế");
        RememberRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RememberRBActionPerformed(evt);
            }
        });

        ForgetBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ForgetBT.setText("Quên mật khẩu");
        ForgetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForgetBTActionPerformed(evt);
            }
        });

        RegisterBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        RegisterBT.setText("Đăng ký");
        RegisterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBTActionPerformed(evt);
            }
        });

        LoginBT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        LoginBT.setText("Đăng nhập");
        LoginBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBTActionPerformed(evt);
            }
        });

        ResetBT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ResetBT.setText("Đặt lại");
        ResetBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBTActionPerformed(evt);
            }
        });

        PosCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách hàng", "Nhân viên" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AccTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(RegisterBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ForgetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RememberRB)
                            .addComponent(PosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassTF, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PosCB, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RememberRB)
                .addGap(21, 21, 21)
                .addComponent(LoginBT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegisterBT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ResetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ForgetBT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(124, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBTActionPerformed
        this.dispose();
        new Register().setVisible(true);
    }//GEN-LAST:event_RegisterBTActionPerformed
    static ConnectionDB kn=new ConnectionDB();
    
    private void LoginBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBTActionPerformed
        Connection c=kn.getConnectionDB();
        Statement stm = null;
        ResultSet rs = null;
        String sql;
        StringBuilder sb = new StringBuilder();
        if (AccTF.getText().equals("")){
                    sb.append("Tên Tài khoản không được bỏ trống! \n");
                }
        if (PassTF.getPassword().toString().equals("")){
                    sb.append("Mật khẩu không được để trống! \n");
                }
        if (sb.length()>0) {
            JOptionPane.showMessageDialog(this, sb.toString(), "Invalidation",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (PosCB.getSelectedItem().equals("Khách hàng")){
            try {
                sql = "select * from KHACHHANG";
                stm=c.createStatement();
                rs=stm.executeQuery(sql);
                while (rs.next()) {
                    if(rs.getString(1).equals(AccTF.getText()) && rs.getString(2).equals(String.valueOf(PassTF.getPassword()))){
                        Writefile();
                        this.dispose();
                        new GDKhach(AccTF.getText()).setVisible(true);
                        return;
                    }
                }
                JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu!", "Invalidation", JOptionPane.ERROR_MESSAGE);
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
        else
        {
            try {
                sql = "select * from NHANVIEN";
                stm=c.createStatement();
                rs=stm.executeQuery(sql);
                while (rs.next()) {
                    if(rs.getString(3).equals(AccTF.getText()) && rs.getString(4).equals(String.valueOf(PassTF.getPassword()))){
                        Writefile();
                        this.dispose();
                        new GDAdmin(AccTF.getText()).setVisible(true);
                        return;
                    }
                }
                JOptionPane.showMessageDialog(this, "Sai tên tài khoản hoặc mật khẩu!", "Invalidation", JOptionPane.ERROR_MESSAGE);
            }
            catch (Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_LoginBTActionPerformed

    private void ResetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBTActionPerformed
        AccTF.setText("");
        PassTF.setText("");
        RememberRB.setSelected(false);
        PosCB.setSelectedItem("Khách hàng");
    }//GEN-LAST:event_ResetBTActionPerformed

    private void RememberRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RememberRBActionPerformed
        try {
            Writefile();
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_RememberRBActionPerformed

    private void ForgetBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForgetBTActionPerformed
        this.dispose();
        new ForgotPass().setVisible(true);
    }//GEN-LAST:event_ForgetBTActionPerformed

    private void Writefile() {
        try{
        PrintWriter pw = new PrintWriter("..\\QL_PHO\\test\\RmbAcc.txt");
            if (RememberRB.isSelected()){
                            acc=AccTF.getText();
                            pass=String.valueOf(PassTF.getPassword());
                        }
                        else {
                            acc="";
                            pass="";
                        }
                        pw.println(acc);
                        pw.println(pass);
                        pw.print(PosCB.getSelectedItem());
                        pw.close();}
        catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    public static void main(String args[]){ 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccTF;
    private javax.swing.JButton ForgetBT;
    private javax.swing.JButton LoginBT;
    private javax.swing.JPasswordField PassTF;
    private javax.swing.JComboBox<String> PosCB;
    private javax.swing.JButton RegisterBT;
    private javax.swing.JRadioButton RememberRB;
    private javax.swing.JButton ResetBT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
